//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies the receiver into out.
func (in *HubPull) DeepCopyInto(out *HubPull) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

func (in *HubPull) DeepCopy() *HubPull {
	if in == nil {
		return nil
	}
	out := new(HubPull)
	in.DeepCopyInto(out)
	return out
}

func (in *HubPull) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *HubPullList) DeepCopyInto(out *HubPullList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]HubPull, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *HubPullList) DeepCopy() *HubPullList {
	if in == nil {
		return nil
	}
	out := new(HubPullList)
	in.DeepCopyInto(out)
	return out
}

func (in *HubPullList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
